#!/usr/bin/env bash

search_dir=./instances
out_dir=./results_julia
script="julia smt.jl"
let time=2*60*60 #in seconds

for filename in "$search_dir"/*
do
    echo Running $filename
    declare outfile=$out_dir/$(basename $filename).out
    $script $time < $filename > $outfile
    echo Finished
    echo $outfile generated
done

